import { Equipment, OreCosts, UpgradeLevel } from './types';

export const ORE_ICONS = {
    shiny: 'https://i.imgur.com/bW5r3Cz.png',
    glowy: 'https://i.imgur.com/3O5v1eQ.png',
    starry: 'https://i.imgur.com/M27A9sE.png'
};

const PLACEHOLDER_ICON = 'https://i.imgur.com/8EAF3f6.png'; // A gear icon

const COMMON_EQUIPMENT_LEVELS_18: UpgradeLevel[] = [
    { level: 2, shiny: 120, glowy: 0, starry: 0 },
    { level: 3, shiny: 240, glowy: 20, starry: 0 },
    { level: 4, shiny: 400, glowy: 0, starry: 0 },
    { level: 5, shiny: 600, glowy: 0, starry: 0 },
    { level: 6, shiny: 840, glowy: 100, starry: 0 },
    { level: 7, shiny: 1120, glowy: 0, starry: 0 },
    { level: 8, shiny: 1440, glowy: 0, starry: 0 },
    { level: 9, shiny: 1800, glowy: 200, starry: 0 },
    { level: 10, shiny: 1900, glowy: 0, starry: 0 },
    { level: 11, shiny: 2000, glowy: 0, starry: 0 },
    { level: 12, shiny: 2100, glowy: 400, starry: 0 },
    { level: 13, shiny: 2200, glowy: 0, starry: 0 },
    { level: 14, shiny: 2300, glowy: 0, starry: 0 },
    { level: 15, shiny: 2400, glowy: 600, starry: 0 },
    { level: 16, shiny: 2500, glowy: 0, starry: 0 },
    { level: 17, shiny: 2600, glowy: 0, starry: 0 },
    { level: 18, shiny: 2700, glowy: 600, starry: 0 },
];

const EPIC_EQUIPMENT_LEVELS_27: UpgradeLevel[] = [
    { level: 2, shiny: 120, glowy: 0, starry: 0 },
    { level: 3, shiny: 240, glowy: 20, starry: 0 },
    { level: 4, shiny: 400, glowy: 0, starry: 0 },
    { level: 5, shiny: 600, glowy: 0, starry: 0 },
    { level: 6, shiny: 840, glowy: 100, starry: 0 },
    { level: 7, shiny: 1120, glowy: 0, starry: 0 },
    { level: 8, shiny: 1440, glowy: 0, starry: 0 },
    { level: 9, shiny: 1800, glowy: 200, starry: 10 },
    { level: 10, shiny: 1900, glowy: 0, starry: 0 },
    { level: 11, shiny: 2000, glowy: 0, starry: 0 },
    { level: 12, shiny: 2100, glowy: 400, starry: 20 },
    { level: 13, shiny: 2200, glowy: 0, starry: 0 },
    { level: 14, shiny: 2300, glowy: 0, starry: 0 },
    { level: 15, shiny: 2400, glowy: 600, starry: 30 },
    { level: 16, shiny: 2500, glowy: 0, starry: 0 },
    { level: 17, shiny: 2600, glowy: 0, starry: 0 },
    { level: 18, shiny: 2700, glowy: 600, starry: 50 },
    { level: 19, shiny: 2800, glowy: 0, starry: 0 },
    { level: 20, shiny: 2900, glowy: 0, starry: 0 },
    { level: 21, shiny: 3000, glowy: 600, starry: 100 },
    { level: 22, shiny: 3100, glowy: 0, starry: 0 },
    { level: 23, shiny: 3200, glowy: 0, starry: 0 },
    { level: 24, shiny: 3300, glowy: 600, starry: 120 },
    { level: 25, shiny: 3400, glowy: 0, starry: 0 },
    { level: 26, shiny: 3500, glowy: 0, starry: 0 },
    { level: 27, shiny: 3600, glowy: 600, starry: 150 },
];


export const EQUIPMENT_DATA: Equipment[] = [
    // Barbarian King
    {
        name: 'Barbarian Puppet',
        hero: 'Barbarian King',
        maxLevel: 18,
        icon: 'https://i.imgur.com/8Q0y7zD.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Rage Vial',
        hero: 'Barbarian King',
        maxLevel: 18,
        icon: 'https://i.imgur.com/kS9v45p.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Earthquake Boots',
        hero: 'Barbarian King',
        maxLevel: 18,
        icon: 'https://i.imgur.com/8VpcK4V.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Vampstache',
        hero: 'Barbarian King',
        maxLevel: 18,
        icon: 'https://i.imgur.com/5n5ODBi.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Giant Gauntlet',
        hero: 'Barbarian King',
        maxLevel: 27,
        icon: 'https://i.imgur.com/3hJzQ7E.png',
        levels: EPIC_EQUIPMENT_LEVELS_27,
    },
    {
        name: 'Spiky Ball',
        hero: 'Barbarian King',
        maxLevel: 27,
        icon: 'https://i.imgur.com/8G0s11d.png',
        levels: EPIC_EQUIPMENT_LEVELS_27,
    },
    {
        name: 'Snake Bracelet',
        hero: 'Barbarian King',
        maxLevel: 27,
        icon: 'https://i.imgur.com/2s44p3d.png',
        levels: EPIC_EQUIPMENT_LEVELS_27,
    },
    // Archer Queen
    {
        name: 'Archer Puppet',
        hero: 'Archer Queen',
        maxLevel: 18,
        icon: 'https://i.imgur.com/t3g0NAl.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Invisibility Vial',
        hero: 'Archer Queen',
        maxLevel: 18,
        icon: 'https://i.imgur.com/j1h0y3t.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Giant Arrow',
        hero: 'Archer Queen',
        maxLevel: 18,
        icon: 'https://i.imgur.com/tOjdI5J.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Healer Puppet',
        hero: 'Archer Queen',
        maxLevel: 18,
        icon: 'https://i.imgur.com/kOfk24m.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Frozen Arrow',
        hero: 'Archer Queen',
        maxLevel: 27,
        icon: 'https://i.imgur.com/QJ2m5m4.png',
        levels: EPIC_EQUIPMENT_LEVELS_27,
    },
    {
        name: 'Magic Mirror',
        hero: 'Archer Queen',
        maxLevel: 27,
        icon: PLACEHOLDER_ICON,
        levels: EPIC_EQUIPMENT_LEVELS_27,
    },
    {
        name: 'Action Figure',
        hero: 'Archer Queen',
        maxLevel: 27,
        icon: PLACEHOLDER_ICON,
        levels: EPIC_EQUIPMENT_LEVELS_27,
    },
    // Grand Warden
    {
        name: 'Eternal Tome',
        hero: 'Grand Warden',
        maxLevel: 18,
        icon: 'https://i.imgur.com/tG2g9sR.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Life Gem',
        hero: 'Grand Warden',
        maxLevel: 18,
        icon: 'https://i.imgur.com/uCgvVYW.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Healing Tome',
        hero: 'Grand Warden',
        maxLevel: 18,
        icon: 'https://i.imgur.com/1aA2n2a.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Rage Gem',
        hero: 'Grand Warden',
        maxLevel: 18,
        icon: 'https://i.imgur.com/8EN1aAp.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
     {
        name: 'Fireball',
        hero: 'Grand Warden',
        maxLevel: 27,
        icon: 'https://i.imgur.com/v8p4s1f.png',
        levels: EPIC_EQUIPMENT_LEVELS_27,
    },
    {
        name: 'Lavaloon Puppet',
        hero: 'Grand Warden',
        maxLevel: 27,
        icon: PLACEHOLDER_ICON,
        levels: EPIC_EQUIPMENT_LEVELS_27,
    },
    {
        name: 'Heroic Torch',
        hero: 'Grand Warden',
        maxLevel: 27,
        icon: PLACEHOLDER_ICON,
        levels: EPIC_EQUIPMENT_LEVELS_27,
    },
    // Royal Champion
    {
        name: 'Seeking Shield',
        hero: 'Royal Champion',
        maxLevel: 18,
        icon: 'https://i.imgur.com/qg9b9eW.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Royal Gem',
        hero: 'Royal Champion',
        maxLevel: 18,
        icon: 'https://i.imgur.com/1G8eQ7h.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Haste Vial',
        hero: 'Royal Champion',
        maxLevel: 18,
        icon: 'https://i.imgur.com/tDD1rD0.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Hog Rider Puppet',
        hero: 'Royal Champion',
        maxLevel: 18,
        icon: 'https://i.imgur.com/AByxV0a.png',
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Rocket Spear',
        hero: 'Royal Champion',
        maxLevel: 27,
        icon: 'https://i.imgur.com/e2Z3a5G.png',
        levels: EPIC_EQUIPMENT_LEVELS_27,
    },
    {
        name: 'Electro Boots',
        hero: 'Royal Champion',
        maxLevel: 27,
        icon: PLACEHOLDER_ICON,
        levels: EPIC_EQUIPMENT_LEVELS_27,
    },
    // Minion Prince
    {
        name: 'Dark Orb',
        hero: 'Minion Prince',
        maxLevel: 18,
        icon: PLACEHOLDER_ICON,
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Henchmen Puppet',
        hero: 'Minion Prince',
        maxLevel: 18,
        icon: PLACEHOLDER_ICON,
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Metal Pants',
        hero: 'Minion Prince',
        maxLevel: 18,
        icon: PLACEHOLDER_ICON,
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Noble Iron',
        hero: 'Minion Prince',
        maxLevel: 18,
        icon: PLACEHOLDER_ICON,
        levels: COMMON_EQUIPMENT_LEVELS_18,
    },
    {
        name: 'Dark Crown',
        hero: 'Minion Prince',
        maxLevel: 27,
        icon: PLACEHOLDER_ICON,
        levels: EPIC_EQUIPMENT_LEVELS_27,
    },
    {
        name: 'Meteor Staff',
        hero: 'Minion Prince',
        maxLevel: 27,
        icon: PLACEHOLDER_ICON,
        levels: EPIC_EQUIPMENT_LEVELS_27,
    },
];

const ICONS = {
    BRONZE: 'https://api-assets.clashofclans.com/leagues/288/u56e0B0002_hD56Q3q3vM31o1PABY15bF_Cj2n_88g.png',
    SILVER: 'https://api-assets.clashofclans.com/leagues/288/n1dIe_8Cj2n_88g_Cj2n_88g_Cj2n_88g_Cj2n_88g.png',
    GOLD: 'https://api-assets.clashofclans.com/leagues/288/Y6CveuHmPM_6O3sl3i4y3Y3y3Y3y3Y3y3Y3y3Y3y.png',
    CRYSTAL: 'https://api-assets.clashofclans.com/leagues/288/k6N3_a4y3Y3y3Y3y3Y3y3Y3y3Y3y3Y3y3Y3y.png',
    MASTER: 'https://api-assets.clashofclans.com/leagues/288/p_3a4y3Y3y3Y3y3Y3y3Y3y3Y3y3Y3y3Y3y.png',
    CHAMPION: 'https://api-assets.clashofclans.com/leagues/288/q_3a4y3Y3y3Y3y3Y3y3Y3y3Y3y3Y3y3Y3y.png',
    TITAN: 'https://api-assets.clashofclans.com/leagues/288/t_3a4y3Y3y3Y3y3Y3y3Y3y3Y3y3Y3y3Y3y.png',
    LEGEND: 'https://api-assets.clashofclans.com/leagues/288/r_3a4y3Y3y3Y3y3Y3y3Y3y3Y3y3Y3y3Y3y.png',
};

export const LEAGUES = [
    { name: 'Skeleton 1', icon: ICONS.BRONZE, dailyStarBonus: { shiny: 300, glowy: 20, starry: 0 } },
    { name: 'Skeleton 2', icon: ICONS.BRONZE, dailyStarBonus: { shiny: 325, glowy: 21, starry: 0 } },
    { name: 'Skeleton 3', icon: ICONS.BRONZE, dailyStarBonus: { shiny: 350, glowy: 22, starry: 0 } },
    { name: 'Barbarian 4', icon: ICONS.SILVER, dailyStarBonus: { shiny: 375, glowy: 23, starry: 0 } },
    { name: 'Barbarian 5', icon: ICONS.SILVER, dailyStarBonus: { shiny: 400, glowy: 24, starry: 0 } },
    { name: 'Barbarian 6', icon: ICONS.SILVER, dailyStarBonus: { shiny: 425, glowy: 25, starry: 0 } },
    { name: 'Archer 7', icon: ICONS.GOLD, dailyStarBonus: { shiny: 450, glowy: 26, starry: 0 } },
    { name: 'Archer 8', icon: ICONS.GOLD, dailyStarBonus: { shiny: 475, glowy: 27, starry: 1 } },
    { name: 'Archer 9', icon: ICONS.GOLD, dailyStarBonus: { shiny: 500, glowy: 29, starry: 1 } },
    { name: 'Wizard 10', icon: ICONS.CRYSTAL, dailyStarBonus: { shiny: 525, glowy: 31, starry: 1 } },
    { name: 'Wizard 11', icon: ICONS.CRYSTAL, dailyStarBonus: { shiny: 550, glowy: 33, starry: 1 } },
    { name: 'Wizard 12', icon: ICONS.CRYSTAL, dailyStarBonus: { shiny: 575, glowy: 35, starry: 1 } },
    { name: 'Valkyrie 13', icon: ICONS.MASTER, dailyStarBonus: { shiny: 600, glowy: 37, starry: 1 } },
    { name: 'Valkyrie 14', icon: ICONS.MASTER, dailyStarBonus: { shiny: 625, glowy: 39, starry: 1 } },
    { name: 'Valkyrie 15', icon: ICONS.MASTER, dailyStarBonus: { shiny: 650, glowy: 41, starry: 1 } },
    { name: 'Witch 16', icon: ICONS.CHAMPION, dailyStarBonus: { shiny: 675, glowy: 43, starry: 1 } },
    { name: 'Witch 17', icon: ICONS.CHAMPION, dailyStarBonus: { shiny: 725, glowy: 45, starry: 1 } },
    { name: 'Witch 18', icon: ICONS.CHAMPION, dailyStarBonus: { shiny: 775, glowy: 47, starry: 1 } },
    { name: 'Golem 19', icon: ICONS.TITAN, dailyStarBonus: { shiny: 825, glowy: 49, starry: 1 } },
    { name: 'Golem 20', icon: ICONS.TITAN, dailyStarBonus: { shiny: 875, glowy: 51, starry: 1 } },
    { name: 'Golem 21', icon: ICONS.TITAN, dailyStarBonus: { shiny: 900, glowy: 53, starry: 1 } },
    { name: 'P.E.K.K.A 22', icon: ICONS.TITAN, dailyStarBonus: { shiny: 925, glowy: 54, starry: 1 } },
    { name: 'P.E.K.K.A 23', icon: ICONS.TITAN, dailyStarBonus: { shiny: 950, glowy: 55, starry: 1 } },
    { name: 'P.E.K.K.A 24', icon: ICONS.TITAN, dailyStarBonus: { shiny: 963, glowy: 56, starry: 1 } },
    { name: 'Titan 25', icon: ICONS.TITAN, dailyStarBonus: { shiny: 1000, glowy: 57, starry: 1 } },
    { name: 'Titan 26', icon: ICONS.TITAN, dailyStarBonus: { shiny: 1010, glowy: 58, starry: 1 } },
    { name: 'Titan 27', icon: ICONS.TITAN, dailyStarBonus: { shiny: 1020, glowy: 59, starry: 1 } },
    { name: 'Dragon 28', icon: ICONS.LEGEND, dailyStarBonus: { shiny: 1030, glowy: 60, starry: 1 } },
    { name: 'Dragon 29', icon: ICONS.LEGEND, dailyStarBonus: { shiny: 1040, glowy: 61, starry: 1 } },
    { name: 'Dragon 30', icon: ICONS.LEGEND, dailyStarBonus: { shiny: 1050, glowy: 62, starry: 1 } },
    { name: 'Electro 31', icon: ICONS.LEGEND, dailyStarBonus: { shiny: 1060, glowy: 62, starry: 2 } },
    { name: 'Electro 32', icon: ICONS.LEGEND, dailyStarBonus: { shiny: 1070, glowy: 63, starry: 2 } },
    { name: 'Electro 33', icon: ICONS.LEGEND, dailyStarBonus: { shiny: 1080, glowy: 64, starry: 2 } },
    { name: 'Legend', icon: ICONS.LEGEND, dailyStarBonus: { shiny: 1100, glowy: 65, starry: 2 } },
];


export const WAR_TOWN_HALL_LOOT: Record<number, { win: OreCosts; loss: OreCosts }> = {
    8: { win: { shiny: 380, glowy: 15, starry: 0 }, loss: { shiny: 190, glowy: 8, starry: 0 }},
    9: { win: { shiny: 410, glowy: 18, starry: 0 }, loss: { shiny: 205, glowy: 9, starry: 0 }},
    10: { win: { shiny: 460, glowy: 21, starry: 3 }, loss: { shiny: 230, glowy: 11, starry: 2 }},
    11: { win: { shiny: 560, glowy: 24, starry: 3 }, loss: { shiny: 280, glowy: 12, starry: 2 }},
    12: { win: { shiny: 610, glowy: 27, starry: 4 }, loss: { shiny: 305, glowy: 14, starry: 2 }},
    13: { win: { shiny: 710, glowy: 30, starry: 4 }, loss: { shiny: 355, glowy: 15, starry: 2 }},
    14: { win: { shiny: 810, glowy: 33, starry: 4 }, loss: { shiny: 405, glowy: 17, starry: 2 }},
    15: { win: { shiny: 960, glowy: 36, starry: 5 }, loss: { shiny: 480, glowy: 18, starry: 3 }},
    16: { win: { shiny: 1110, glowy: 39, starry: 6 }, loss: { shiny: 555, glowy: 20, starry: 3 }},
    17: { win: { shiny: 1110, glowy: 39, starry: 6 }, loss: { shiny: 555, glowy: 20, starry: 3 }},
};

export const TRADER_ORE_PURCHASE = {
    shiny: 500,
    glowy: 50,
    starry: 5,
};

export const TRADER_GEMS_ORE_PURCHASE = {
    shiny: 300,
    glowy: 60,
    starry: 15,
    freeGlowy: 10,
};
